export const mockNotes = [
  {
    color: 'lime',
    isPublic: false,
    owner: 'Samir',
    tags: ['tag1', 'tag23', 'tag34'],
    text: 'text1',
    title: 'title1',
    id: 1,
  },
  {
    color: 'steelblue',
    isPublic: false,
    owner: 'Samir',
    tags: ['tag1'],
    text: 'text2',
    title: 'title2',
    id: 2,
  },
  {
    color: 'tomato',
    isPublic: true,
    owner: 'Samir',
    tags: ['tag2'],
    text: 'text3',
    title: 'title3',
    id: 3,
  },
  {
    color: 'orange',
    isPublic: false,
    owner: 'Samir',
    tags: ['tag2'],
    text: 'text4',
    title: 'title4',
    id: 4,
  },
]
